# render.yaml

services:
  - type: web
    name: imcomp
    runtime: node
    buildCommand: |
      rm -rf node_modules
      rm package-lock.json
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production