# render.yaml

services:
  - type: web
    name: imcomp
    buildCommand: |
      rm -rf node_modules
      rm package-lock.json
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    buildNodeVersion: 20.9.0
